apiVersion: v1
kind: Service
metadata:
  name: go-api
  namespace: default
  labels:
    app: go-api
    env: production
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: go-api
