apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-helm
  namespace: argocd
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/fr-mei/app-deploy-configs.git
    path: infrastructure/kong/helm-charts/kong
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
