apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-config
  namespace: argocd
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/fr-mei/app-deploy-configs.git
    path: infrastructure/kong/apps/production
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
