apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fr-mei/app-deploy-configs.git
    path: infrastructure/kong
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /status
  - group: batch
    kind: Job
    jsonPointers:
    - /status
