apiVersion: v2
name: kong
description: Kong API Gateway installation with GitOps
type: application
version: 0.1.0
appVersion: "3.6.0"
dependencies:
- name: kong
  version: "2.38.0"
  repository: "https://charts.konghq.com"
